# goal definition
string goal # `check map`, `update topology`, `get next poi`, `goto room`, `goto corridor`, `goto recharge point`, `survey room`, `survey corridor`, `charge battery`
---
# result definition
string result 
---
# feedback
string task_state # base message that would be changed later based on project requirements. 